import os
import json
import shutil

langs = ['en', 'fr', 'it', 'es', 'de', 'pt_BR', 'pt_PT', 'pl', 'ru', 'ja', 'ko', 'zh_CN', 'zh_TW']

messages = {
  "extName": { "en": "Content Analyzer", "es": "Analizador de contenido", "fr": "Analyseur de contenu", "it": "Analizzatore di contenuti", "de": "Inhaltsanalysator", "pt": "Analisador de conteúdo", "pl": "Analizator treści", "ru": "Анализатор контента", "ja": "コンテンツアナライザー", "ko": "콘텐츠 분석기", "zh": "内容分析器" },
  "extDesc": { "en": "Processes selected content with AI", "es": "Procesa contenido seleccionado con IA", "fr": "Traite le contenu sélectionné avec l'IA", "it": "Elabora i contenuti selezionati con l'IA", "de": "Verarbeitet ausgewählte Inhalte mit KI", "pt": "Processa conteúdo selecionado com IA", "pl": "Przetwarza wybraną treść za pomocą AI", "ru": "Обрабатывает выбранный контент с помощью ИИ", "ja": "選択したコンテンツをAIで処理します", "ko": "AI로 선택한 콘텐츠를 처리합니다", "zh": "使用 AI 处理所选内容" },
  "popupTitle": { "en": "Analyze Content", "es": "Analizar Contenido", "fr": "Analyser le contenu", "it": "Analizza contenuto", "de": "Inhalte analysieren", "pt": "Analisar Conteúdo", "pl": "Analizuj treść", "ru": "Анализировать контент", "ja": "コンテンツを分析", "ko": "콘텐츠 분석", "zh": "分析内容" },
  "selectService": { "en": "AI Service:", "es": "Procesar con IA", "fr": "Traiter avec l'IA", "it": "Elabora con IA", "de": "Mit KI verarbeiten", "pt": "Processar com IA", "pl": "Przetwarzaj z AI", "ru": "Обработка с помощью ИИ", "ja": "AIで処理", "ko": "AI로 처리", "zh": "AI处理" },
  "btnExtractBrowser": { "en": "Extract in browser", "es": "Extraer en navegador", "fr": "Extraire dans le navigateur", "it": "Estrai nel browser", "de": "Im Browser extrahieren", "pt": "Extrair no navegador", "pl": "Wyodrębnij w przeglądarce", "ru": "Извлечь в браузере", "ja": "ブラウザで抽出", "ko": "브라우저에서 추출", "zh": "在浏览器中提取" },
  "btnExtractDisk": { "en": "Save to disk (.md)", "es": "Grabar en disco", "fr": "Enregistrer sur le disque", "it": "Salva su disco", "de": "Auf Festplatte speichern", "pt": "Salvar no disco", "pl": "Zapisz na dysku", "ru": "Сохранить на диск", "ja": "ディスクに保存", "ko": "디스크에 저장", "zh": "保存到本地" },
  "statusProcessing": { "en": "Processing...", "es": "Procesando...", "fr": "Traitement...", "it": "Elaborazione...", "de": "Wird bearbeitet...", "pt": "Processando...", "pl": "Przetwarzanie...", "ru": "Обработка...", "ja": "処理中...", "ko": "처리 중...", "zh": "处理中..." },
  "statusSaved": { "en": "Saved to downloads", "es": "Guardado en descargas", "fr": "Enregistré dans les téléchargements", "it": "Salvato nei download", "de": "In Downloads gespeichert", "pt": "Salvo nos downloads", "pl": "Zapisano w pobranych", "ru": "Сохранено в загрузках", "ja": "ダウンロードに保存", "ko": "다운로드에 저장됨", "zh": "已保存到下载" },
  "statusSelectService": { "en": "Select provider", "es": "Seleccione proveedor", "fr": "Sélectionnez le fournisseur", "it": "Seleziona fornitore", "de": "Anbieter auswählen", "pt": "Selecione o provedor", "pl": "Wybierz dostawcę", "ru": "Выберите провайдера", "ja": "プロバイダを選択", "ko": "제공자 선택", "zh": "选择提供商" },
  "optPageTitle": { "en": "Configure services", "es": "Configurar servicios", "fr": "Configurer les services", "it": "Configura servizi", "de": "Dienste konfigurieren", "pt": "Configurar serviços", "pl": "Skonfiguruj usługi", "ru": "Настроить службы", "ja": "サービスを構成", "ko": "서비스 구성", "zh": "配置服务" },
  "optTitle": { "en": "AI Configuration", "es": "Configuración de IA", "fr": "Configuration IA", "it": "Configurazione IA", "de": "KI-Konfiguration", "pt": "Configuração de IA", "pl": "Konfiguracja AI", "ru": "Настройки ИИ", "ja": "AI設定", "ko": "AI 설정", "zh": "AI 配置" },
  "optAddService": { "en": "Add New Service", "es": "Añadir Nuevo Servicio", "fr": "Ajouter un nouveau service", "it": "Aggiungi nuovo servizio", "de": "Neuen Dienst hinzufügen", "pt": "Adicionar Novo Serviço", "pl": "Dodaj nową usługę", "ru": "Добавить новую службу", "ja": "新しいサービスを追加", "ko": "새 서비스 추가", "zh": "添加新服务" },
  "optNameLabel": { "en": "Identifier Name", "es": "Nombre identificativo", "fr": "Nom d'identification", "it": "Nome identificativo", "de": "Kennziffer Name", "pt": "Nome identificador", "pl": "Nazwa identyfikacyjna", "ru": "Название сервиса", "ja": "識別名", "ko": "식별 이름", "zh": "标识名称" },
  "optNamePlaceholder": { "en": "Ex: Ollama Llama3 Summary", "es": "Ej: Ollama Llama3 Resumen", "fr": "Ex : Résumé Ollama Llama3", "it": "Es: Riassunto Ollama Llama3", "de": "Bsp: Ollama Llama3 Zusammenfassung", "pt": "Ex: Ollama Llama3 Resumo", "pl": "Nadz: Ollama Llama3 Podsumowanie", "ru": "Например: Резюме Ollama Llama3", "ja": "例：Ollama Llama3 要約", "ko": "예: Ollama Llama3 요약", "zh": "例：Ollama Llama3 摘要" },
  "optTypeLabel": { "en": "Type", "es": "Tipo", "fr": "Type", "it": "Tipo", "de": "Typ", "pt": "Tipo", "pl": "Typ", "ru": "Тип", "ja": "タイプ", "ko": "유형", "zh": "类型" },
  "optUrlLabel": { "en": "Service URL", "es": "URL del Servicio", "fr": "URL du service", "it": "URL del Servizio", "de": "Dienst-URL", "pt": "URL do Serviço", "pl": "URL Usługi", "ru": "URL службы", "ja": "サービス URL", "ko": "서비스 URL", "zh": "服务 URL" },
  "optUrlHint": { "en": "Available models will be queried when typing the URL.", "es": "Al escribir la URL se consultarán los modelos disponibles.", "fr": "Les modèles disponibles seront interrogés lors de la saisie de l'URL.", "it": "I modelli disponibili saranno interrogati quando si digita l'URL.", "de": "Verfügbare Modelle werden bei der Eingabe der URL abgefragt.", "pt": "Os modelos disponíveis serão consultados ao digitar o URL.", "pl": "Dostępne modele zostaną przeszukane po wpisaniu adresu URL.", "ru": "При вводе URL-адреса будут запрошены доступные модели.", "ja": "URLを入力すると、利用可能なモデルが照会されます。", "ko": "URL을 입력하면 사용 가능한 모델이 조회됩니다。", "zh": "输入 URL 时将查询可用模型。" },
  "optApiKeyLabel": { "en": "API Key (optional)", "es": "Clave de API (opcional)", "fr": "Clé API (facultatif)", "it": "Chiave API (opzionale)", "de": "API-Schlüssel (optional)", "pt": "Chave API (opcional)", "pl": "Klucz API (opcjonalnie)", "ru": "Ключ API (необязательно)", "ja": "API キー（オプション）", "ko": "API 키(선택 사항)", "zh": "API 密钥（可选）" },
  "optModelLabel": { "en": "Model to use", "es": "Modelo a usar", "fr": "Modèle à utiliser", "it": "Modello da utilizzare", "de": "Zu verwendendes Modell", "pt": "Modelo a utilizar", "pl": "Model do użycia", "ru": "Модель для использования", "ja": "使用するモデル", "ko": "사용할 모델", "zh": "使用的模型" },
  "optModelEmpty": { "en": "-- Enter valid config --", "es": "-- Introduce configuración válida --", "fr": "-- Entrez une configuration valide --", "it": "-- Inserisci config valida --", "de": "-- Gültige Konfiguration eingeben --", "pt": "-- Insira uma configuração válida --", "pl": "-- Wprowadź prawidłową konfigurację --", "ru": "-- Введите действительную конфигурацию --", "ja": "-- 有効な構成を入力 --", "ko": "-- 올바른 구성 입력 --", "zh": "-- 输入有效的配置 --" },
  "optModelLoading": { "en": "Loading services...", "es": "Cargando servicios...", "fr": "Chargement des services...", "it": "Caricamento servizi...", "de": "Dienste werden geladen...", "pt": "Carregando serviços...", "pl": "Ładowanie usług...", "ru": "Загрузка служб...", "ja": "サービスをロード中...", "ko": "서비스 로드 중...", "zh": "加载服务中..." },
  "optPromptLabel": { "en": "Prompt", "es": "Prompt", "fr": "Prompt", "it": "Prompt", "de": "Forderung", "pt": "Prompt", "pl": "Podpowiedź", "ru": "Промпт", "ja": "プロンプト", "ko": "프롬프트", "zh": "提示词" },
  "optPromptPlaceholder": { "en": "Analyze this text and give me your conclusions", "es": "Analiza este texto y dime tus conclusiones", "fr": "Analysez ce texte et donnez-moi vos conclusions", "it": "Analizza questo testo e dimmi le tue conclusioni", "de": "Analysieren Sie diesen Text und geben Sie mir Ihre Schlussfolgerungen", "pt": "Analise este texto e dê-me as suas conclusões", "pl": "Przeanalizuj ten tekst i podaj mi swoje wnioski", "ru": "Проанализируй этот текст и сделай выводы", "ja": "このテキストを分析し、結論を出してください", "ko": "이 텍스트를 분석하고 결론을 알려주세요", "zh": "分析这段文字并给出你的结论" },
  "optSaveBtn": { "en": "Save Service", "es": "Guardar Servicio", "fr": "Enregistrer le service", "it": "Salva servizio", "de": "Dienst speichern", "pt": "Salvar Serviço", "pl": "Zapisz usługę", "ru": "Сохранить службу", "ja": "サービスを保存", "ko": "서비스 저장", "zh": "保存服务" },
  "optCancelBtn": { "en": "Cancel", "es": "Cancelar", "fr": "Annuler", "it": "Annulla", "de": "Stornieren", "pt": "Cancelar", "pl": "Anuluj", "ru": "Отмена", "ja": "キャンセル", "ko": "취소", "zh": "取消" },
  "optListTitle": { "en": "Configured Services", "es": "Servicios Configurados", "fr": "Services configurés", "it": "Servizi configurati", "de": "Konfigurierte Dienste", "pt": "Serviços Configurados", "pl": "Skonfigurowane usługi", "ru": "Настроенные службы", "ja": "構成されたサービス", "ko": "구성된 서비스", "zh": "配置的服务" },
  "thName": { "en": "Name", "es": "Nombre", "fr": "Nom", "it": "Nome", "de": "Name", "pt": "Nome", "pl": "Nazwa", "ru": "Имя", "ja": "名前", "ko": "이름", "zh": "名字" },
  "thType": { "en": "Type", "es": "Tipo", "fr": "Type", "it": "Tipo", "de": "Typ", "pt": "Tipo", "pl": "Typ", "ru": "Тип", "ja": "タイプ", "ko": "유형", "zh": "类型" },
  "thUrl": { "en": "URL", "es": "URL", "fr": "URL", "it": "URL", "de": "URL", "pt": "URL", "pl": "URL", "ru": "URL", "ja": "URL", "ko": "URL", "zh": "URL" },
  "thDomains": { "en": "Linked domains", "es": "Dominios vinculados", "fr": "Domaines liés", "it": "Domini collegati", "de": "Verknüpfte Domänen", "pt": "Domínios vinculados", "pl": "Połączone domeny", "ru": "Связанные домены", "ja": "リンクされたドメイン", "ko": "연결된 도메인", "zh": "关联域名" },
  "thModel": { "en": "Model", "es": "Modelo", "fr": "Modèle", "it": "Modello", "de": "Modell", "pt": "Modelo", "pl": "Model", "ru": "Модель", "ja": "モデル", "ko": "모델", "zh": "模型" },
  "thActions": { "en": "Actions", "es": "Acciones", "fr": "Actions", "it": "Azioni", "de": "Aktionen", "pt": "Ações", "pl": "Akcje", "ru": "Действия", "ja": "アクション", "ko": "작업", "zh": "操作" },
  "btnEdit": { "en": "Edit", "es": "Editar", "fr": "Modifier", "it": "Modifica", "de": "Bearbeiten", "pt": "Editar", "pl": "Edycja", "ru": "Изменить", "ja": "編集", "ko": "편집", "zh": "编辑" },
  "btnDelete": { "en": "Delete", "es": "Eliminar", "fr": "Supprimer", "it": "Elimina", "de": "Löschen", "pt": "Excluir", "pl": "Usuń", "ru": "Удалить", "ja": "削除", "ko": "삭제", "zh": "删除" },
  "alertServiceExists": { "en": "Service with that name already exists", "es": "Ya existe un servicio con ese nombre", "fr": "Un service avec ce nom existe déjà", "it": "Esiste già un servizio con questo nome", "de": "Es existiert bereits ein Dienst mit diesem Namen", "pt": "Já existe um serviço com esse nome", "pl": "Usługa o tej nazwie już istnieje", "ru": "Служба с таким именем уже существует", "ja": "その名前のサービスはすでに存在します", "ko": "해당 이름의 서비스가 이미 존재합니다", "zh": "具有该名称服务已存在" },
  "resPageTitle": { "en": "AI Result - Analyzer", "es": "Resultado IA - Analizador", "fr": "Résultat IA - Analyseur", "it": "Risultato IA - Analizzatore", "de": "KI-Ergebnis - Analysator", "pt": "Resultado IA - Analisador", "pl": "Wynik AI - Analizator", "ru": "Результат ИИ - Анализатор", "ja": "AI結果 - アナライザー", "ko": "AI 결과 - 분석기", "zh": "AI 结果 - 分析器" },
  "resHeader": { "en": "Result - ", "es": "Resultado - ", "fr": "Résultat - ", "it": "Risultato - ", "de": "Ergebnis - ", "pt": "Resultado - ", "pl": "Wynik - ", "ru": "Результат - ", "ja": "結果 - ", "ko": "결과 - ", "zh": "结果 - " },
  "resSaving": { "en": "Saving...", "es": "Guardando...", "fr": "Enregistrement...", "it": "Salvataggio...", "de": "Speichern...", "pt": "Salvando...", "pl": "Zapisywanie...", "ru": "Сохранение...", "ja": "保存中...", "ko": "저장 중...", "zh": "保存中..." },
  "resSaveBtn": { "en": "Save as Markdown", "es": "Guardar en archivo", "fr": "Enregistrer sous", "it": "Salva come file", "de": "Als Markdown speichern", "pt": "Salvar como arquivo", "pl": "Zapisz jako Markdown", "ru": "Сохранить как файл", "ja": "ファイルとして保存", "ko": "파일로 저장", "zh": "另存为文件" },
  "resInvalidId": { "en": "Invalid execution ID.", "es": "ID de ejecución no válido.", "fr": "ID d'exécution invalide.", "it": "ID esecuzione errato.", "de": "Ungültige Ausführungs-ID.", "pt": "ID de execução inválido.", "pl": "Nieprawidłowy ID.", "ru": "Недействительный ID.", "ja": "無効なID。", "ko": "잘못된 ID입니다.", "zh": "无效 ID。" },
  "resDataNotFound": { "en": "Article data not found.", "es": "No se encontraron los datos del artículo.", "fr": "Données de l'article introuvables.", "it": "Dati articolo non trovati.", "de": "Artikeldaten nicht gefunden.", "pt": "Dados do artigo não encontrados.", "pl": "Nie znaleziono danych artykułu.", "ru": "Данные статьи не найдены.", "ja": "記事データが見つかりません。", "ko": "기사 데이터를 찾을 수 없습니다.", "zh": "未找到文章数据。" },
  "resReconnecting": { "en": "Retrying query... (Attempt $1/$2)", "es": "Reintentando consulta... (Intento $1/$2)", "fr": "Nouvelle tentative... (Tentative $1/$2)", "it": "Nuovo tentativo... (Tentativo $1/$2)", "de": "Wiederhole Anfrage... (Versuch $1/$2)", "pt": "Tentando novamente... (Tentativa $1/$2)", "pl": "Ponawiam zapytanie... (Próba $1/$2)", "ru": "Повторная попытка... (Попытка $1/$2)", "ja": "再試行しています... (試行 $1/$2)", "ko": "쿼리 재시도 중... ($1/$2 번째 시도)", "zh": "正在重试查询...（尝试 $1/$2）" },
  "resConnError": { "en": "Error: Unexpectedly closed repeatedly.", "es": "Error: La conexión se cerró inesperadamente de forma repetida.", "fr": "Erreur : La connexion s'est fermée de manière inattendue de manière répétée.", "it": "Errore: La connessione si è chiusa inaspettatamente più volte.", "de": "Fehler: Die Verbindung wurde wiederholt unerwartet geschlossen.", "pt": "Erro: A conexão foi fechada inesperadamente várias vezes.", "pl": "Błąd: Połączenie zostało wielokrotnie niespodziewanie zamknięte.", "ru": "Ошибка: Соединение неоднократно прерывалось.", "ja": "エラー：接続が予期せず繰り返し切断されました。", "ko": "오류: 연결이 예기치 않게 계속 닫혔습니다.", "zh": "错误：连接反复意外关闭。" },
  "resAIError": { "en": "AI Error: $1", "es": "Error al comunicarse con la IA: $1", "fr": "Erreur IA: $1", "it": "Errore IA: $1", "de": "KI-Fehler: $1", "pt": "Erro IA: $1", "pl": "Błąd AI: $1", "ru": "Ошибка ИИ: $1", "ja": "AIエラー: $1", "ko": "AI 오류: $1", "zh": "AI 错误: $1" },
  "resDefaultFilename": { "en": "ai_response", "es": "respuesta_ia", "fr": "reponse_ia", "it": "risposta_ia", "de": "ki_antwort", "pt": "resposta_ia", "pl": "odpowiedz_ai", "ru": "ответ_ии", "ja": "ai_応答", "ko": "ai_응답", "zh": "ai_响应" },
  "errUnsupportedService": { "en": "Unsupported service: $1", "es": "Servicio no soportado: $1", "fr": "Service non pris en charge: $1", "it": "Servizio non supportato: $1", "de": "Nicht unterstützter Dienst: $1", "pt": "Serviço não suportado: $1", "pl": "Nieobsługiwana usługa: $1", "ru": "Неподдерживаемая служба: $1", "ja": "サポートされていないサービス: $1", "ko": "지원되지 않는 서비스: $1", "zh": "不支持的服务: $1" },
  "errDownload": { "en": "Download error", "es": "Error en descarga", "fr": "Erreur de téléchargement", "it": "Errore di download", "de": "Download-Fehler", "pt": "Erro no download", "pl": "Błąd pobierania", "ru": "Ошибка загрузки", "ja": "ダウンロードエラー", "ko": "다운로드 오류", "zh": "下载错误" },
  "extIconTitle": { "en": "Analyze Content", "es": "Analizar Contenido", "fr": "Analyser le contenu", "it": "Analizza contenuto", "de": "Inhalte analysieren", "pt": "Analisar Conteúdo", "pl": "Analizuj treść", "ru": "Анализировать контент", "ja": "コンテンツを分析", "ko": "콘텐츠 분석", "zh": "分析内容" },
  "errNoServices": { "en": "No active services.", "es": "No hay servicios activos.", "fr": "Aucun service actif.", "it": "Nessun servizio attivo.", "de": "Keine aktiven Dienste.", "pt": "Nenhum serviço ativo.", "pl": "Brak aktywnych usług.", "ru": "Нет активных служб.", "ja": "アクティブなサービスはありません。", "ko": "활성 서비스가 없습니다.", "zh": "没有活动的服务。" },
  "errNoModels": { "en": "No models found", "es": "No hay modelos", "fr": "Aucun modele trouve", "it": "Nessun modello trovato", "de": "Keine modelle gefunden", "pt": "Modelos nao encontrados", "pl": "Nie znaleziono", "ru": "Нет моделей", "ja": "モデルなし", "ko": "모델 없음", "zh": "没有模型" },
  "errConn": { "en": "Connection error", "es": "Error al conectar", "fr": "Erreur", "it": "Errore", "de": "Fehler", "pt": "Erro", "pl": "Błąd", "ru": "Ошибка", "ja": "エラー", "ko": "오류", "zh": "错误" },
  "optEditService": { "en": "Edit Service", "es": "Editar Servicio", "fr": "Editer", "it": "Modifica", "de": "Bearbeiten", "pt": "Editar", "pl": "Edytuj", "ru": "Изменить", "ja": "編集", "ko": "편집", "zh": "编辑" },
  "optSaveChanges": { "en": "Save Changes", "es": "Guardar Cambios", "fr": "Sauvegarder", "it": "Salva", "de": "Speichern", "pt": "Salvar", "pl": "Zapisz", "ru": "Сохранить", "ja": "保存", "ko": "저장", "zh": "保存" },
  "errNoTab": { "en": "No active tab", "es": "No hay pestaña activa", "fr": "Aucun onglet actif", "it": "Nessuna scheda attiva", "de": "Kein aktiver Tab", "pt": "Nenhuma aba ativa", "pl": "Brak aktywnej karty", "ru": "Нет активной вкладки", "ja": "アクティブなタブがありません", "ko": "활성 탭 없음", "zh": "没有活动标签页" },
  "errParse": { "en": "Capture error: $1", "es": "Error al parsear el elemento: $1", "fr": "Erreur d'analyse: $1", "it": "Errore di analisi: $1", "de": "Fehler beim Parsen: $1", "pt": "Erro ao analisar o elemento: $1", "pl": "Błąd parsowania: $1", "ru": "Ошибка парсинга: $1", "ja": "解析エラー: $1", "ko": "구문 분석 오류: $1", "zh": "解析错误：$1" },
  "tipInstruction": { "en": "🤖 Point to the section to extract and CLICK", "es": "🤖 Apunta a la sección a extraer y haz CLIC", "fr": "🤖 Pointez la section à extraire et CLIQUEZ", "it": "🤖 Punta alla sezione da estrarre e CLICCA", "de": "🤖 Zeigen Sie auf den zu extrahierenden Bereich und KLICKEN Sie", "pt": "🤖 Aponte para a seção a extrair e CLIQUE", "pl": "🤖 Wskaż sekcję do wyodrębnienia i KLIKNIJ", "ru": "🤖 Наведите на раздел для извлечения и НАЖМИТЕ", "ja": "🤖 抽出するセクションをポイントしてクリックします", "ko": "🤖 추출할 섹션을 가리키고 클릭하세요.", "zh": "🤖 指向要提取的部分并点击" },
  "capAllBtn": { "en": "Capture entire page", "es": "Capturar página entera", "fr": "Capturer toute la page", "it": "Cattura l'intera pagina", "de": "Ganze Seite erfassen", "pt": "Capturar página inteira", "pl": "Zdobądź całą stronę", "ru": "Захватить всю страницу", "ja": "ページ全体をキャプチャ", "ko": "전체 페이지 갈무리", "zh": "截取整个页面" }
}

for base_dir in ['content-analyzer-ext-chrome', 'content-analyzer-ext-firefox']:
    locales_dir = os.path.join(base_dir, '_locales')
    
    # Clean up old invalid locales
    for invalid in ['pt', 'zh']:
        invalid_path = os.path.join(locales_dir, invalid)
        if os.path.exists(invalid_path):
            shutil.rmtree(invalid_path)
    
    os.makedirs(locales_dir, exist_ok=True)
    for lang in langs:
        lang_dir = os.path.join(locales_dir, lang)
        os.makedirs(lang_dir, exist_ok=True)
        
        # map generic zh and pt to specific ones if present
        source_lang = lang
        if lang.startswith('pt_'): source_lang = 'pt'
        if lang.startswith('zh_'): source_lang = 'zh'
        
        obj = {}
        for key, transObj in messages.items():
            obj[key] = { "message": transObj.get(source_lang, transObj['en']) }
            
        with open(os.path.join(lang_dir, 'messages.json'), 'w', encoding='utf-8') as f:
            json.dump(obj, f, indent=2, ensure_ascii=False)

print("Locales generated successfully with standardized locale names!")
