/**
 * @file drivers/gemini.js
 * @description Communication driver with the Google Gemini API.
 *
 * This module allows the extension to interact with the Gemini family
 * language models from Google (gemini-1.5-pro, gemini-1.5-flash, etc.)
 * through the Google AI public API (generativelanguage.googleapis.com).
 *
 * AUTHENTICATION:
 * --------------
 * The Gemini API does not use Bearer tokens in headers, but requires
 * passing the API key directly as a query string parameter `?key=`:
 *   https://generativelanguage.googleapis.com/v1beta/models?key=AIzaSy...
 *
 * ENDPOINTS USED:
 * -----------------
 * - GET  /v1beta/models?key=...
 *     Lists available models. Response includes models like
 *     "models/gemini-1.5-pro", "models/gemini-1.5-flash", etc.
 *
 * - POST /v1beta/models/{model}:streamGenerateContent?key=...&alt=sse
 *     Generates content in streaming mode. The `alt=sse` parameter enables
 *     Server-Sent Events (SSE) mode.
 *
 * GENERATION BODY FORMAT:
 * -----------------------------------
 * Gemini uses a "contents" format with parts, different from OpenAI/Anthropic:
 *   {
 *     "contents": [
 *       { "role": "user", "parts": [{ "text": "prompt here" }] }
 *     ]
 *   }
 *
 * STREAM FORMAT (SSE):
 * --------------------------
 * `data:` lines contain JSON objects with the following relevant structure:
 *   {
 *     "candidates": [
 *       {
 *         "content": {
 *           "parts": [{ "text": "generated snippet" }]
 *         }
 *       }
 *     ]
 *   }
 */

/**
 * Retrieves the list of available models from the Google Gemini API.
 *
 * The "models/" prefix returned by the API is removed to expose only
 * the clean model ID (e.g.: "gemini-1.5-flash" instead of "models/gemini-1.5-flash").
 *
 * @param {Object} config - Connection configuration.
 * @param {string} config.apikey - Google AI Studio API key.
 * @returns {Promise<Array<{name: string}>>} List of models with a `name` property.
 * @throws {Error} If the HTTP response is an error.
 */
export async function fetchModels(config) {
    // API key is passed as a query parameter, not an authentication header
    const fetchUrl = `https://generativelanguage.googleapis.com/v1beta/models?key=${config.apikey}`;
    const res = await fetch(fetchUrl);
    if (!res.ok) throw new Error("HTTP " + res.status);
    const data = await res.json();

    // Response looks like: { "models": [ { "name": "models/gemini-1.5-pro", ... }, ... ] }
    // Remove "models/" prefix to get clean ID used in requests.
    if (data.models) {
        return data.models.map(m => ({ name: m.name.replace('models/', '') }));
    }
    return [];
}

/**
 * Generates text from a prompt using the Gemini API with SSE streaming.
 *
 * Uses the `streamGenerateContent` endpoint with `alt=sse` to receive the response
 * incrementally and emit (`yield`) it snippet by snippet.
 *
 * @param {Object} config  - Service configuration.
 * @param {string} config.apikey - Google AI Studio API key.
 * @param {string} config.model  - Clean model ID (without "models/" prefix).
 * @param {string} prompt  - Full prompt text.
 * @yields {string} Text snippets as generated by the model.
 * @throws {Error} If the initial HTTP response is an error.
 */
export async function* generate(config, prompt) {
    // Model is included in URL. The `alt=sse` parameter enables SSE format.
    // Without `alt=sse`, the API returns a full JSON array upon finishing (no streaming).
    const fetchUrl = `https://generativelanguage.googleapis.com/v1beta/models/${config.model}:streamGenerateContent?key=${config.apikey}&alt=sse`;

    const headers = { "Content-Type": "application/json" };

    // Gemini specific body format: "contents" with nested "parts".
    // "user" role indicates message comes from human in conversation.
    const bodyParams = {
        contents: [
            {
                role: "user",
                parts: [{ text: prompt }]
            }
        ]
    };

    const response = await fetch(fetchUrl, {
        method: "POST",
        headers: headers,
        body: JSON.stringify(bodyParams)
    });

    if (!response.ok) throw new Error(`HTTP ${response.status}`);

    const reader = response.body.getReader();
    const decoder = new TextDecoder("utf-8");
    let buffer = ""; // Accumulates partial network data until complete

    while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        // Decode byte chunk and add to accumulated buffer
        buffer += decoder.decode(value, { stream: true });

        // Split by lines since SSE sends data line by line
        let lines = buffer.split("\n");
        buffer = lines.pop(); // The last line might be incomplete: keep it

        for (const line of lines) {
            const tLine = line.trim();
            if (!tLine) continue; // Empty line breaks: separators between SSE events

            if (tLine.startsWith("data: ")) {
                const textData = tLine.substring(6); // Extract JSON after "data: "
                try {
                    const json = JSON.parse(textData);

                    // Navigate the nested Gemini response structure:
                    // candidates[0].content.parts[0].text
                    // Check each level to avoid errors if any are undefined.
                    if (
                        json.candidates &&
                        json.candidates[0] &&
                        json.candidates[0].content &&
                        json.candidates[0].content.parts.length > 0
                    ) {
                        yield json.candidates[0].content.parts[0].text;
                    }
                } catch (e) {
                    // Ignore parsing errors from incomplete or malformed SSE lines
                }
            }
        }
    }
}
