/**
 * @file drivers/ollama.js
 * @description Communication driver with the local Ollama API.
 *
 * Ollama is a language model inference server (LLM) that runs
 * locally on the user's machine. It exposes an HTTP REST API, allowing
 * the extension to communicate with it like a normal web service, without requiring
 * API keys (although optional Bearer token authentication can be configured).
 *
 * RELEVANT OLLAMA API:
 * -------------------------
 * - GET  /api/tags         → List of locally installed models.
 * - POST /api/generate     → Generates text from a prompt (streaming mode).
 * - POST /api/chat         → Multi-turn chat (not used here).
 *
 * NOTE ON CORS AND LOCAL NETWORK:
 * -----------------------------
 * Ollama by default only accepts requests from localhost. To use it from
 * a local network IP (e.g.: 192.168.x.x), it must be started with:
 *   OLLAMA_ORIGINS="*" ollama serve
 * The extension allows configuring the full base URL (including IP and port)
 * on the options page.
 *
 * STREAM FORMAT:
 * --------------------
 * With `stream: true`, Ollama returns the response as a sequence of JSON objects,
 * one per line (NDJSON - Newline-Delimited JSON). Each line looks like this:
 *   {"model":"llama3","response":"text ","done":false}
 *   ...
 *   {"model":"llama3","response":"","done":true}
 *
 * The `done: true` field in the last object indicates that generation has finished.
 * We extract the `response` field from each object and emit it as a text chunk.
 */

/**
 * Retrieves the list of models installed on the Ollama server.
 *
 * Calls the `/api/tags` endpoint which returns a JSON with all models downloaded
 * locally. Each model includes its name, size, and metadata.
 *
 * @param {Object} config - Connection options.
 * @param {string} config.url    - Ollama server base URL (e.g.: "http://localhost:11434").
 * @param {string} [config.apikey] - Optional API key for Bearer authentication.
 * @returns {Promise<Array<{name: string}>>} List of models with at least a `name` property.
 * @throws {Error} If the HTTP response is an error (status >= 400).
 */
export async function fetchModels(config) {
    // Normalize URL by removing the trailing slash to avoid URLs like "localhost//api/tags"
    let url = config.url || "";
    if (url.endsWith("/")) url = url.slice(0, -1);

    const fetchUrl = url + "/api/tags"; // Standard Ollama model catalog endpoint

    // Headers are empty by default; Ollama doesn't require authentication in local setup
    const res = await fetch(fetchUrl);
    if (!res.ok) throw new Error("HTTP " + res.status);

    const data = await res.json();

    // The response looks like: { "models": [ { "name": "llama3:latest", ... }, ... ] }
    // We return the full array of model objects as provided by Ollama,
    // as options.js code expects to access `.name` on each element.
    return data.models || [];
}

/**
 * Generates text from a prompt using Ollama's `/api/generate` endpoint.
 *
 * This function is an async generator. Instead of waiting for the model
 * to finish generating the entire response and returning it at once,
 * it emits (`yield`) text snippets ("chunks") as they arrive from the server.
 * This allows showing the response to the user progressively, character by character.
 *
 * @param {Object} config  - Connection and model options.
 * @param {string} config.url    - Ollama server base URL.
 * @param {string} config.model  - Name of the model to use (e.g.: "llama3:latest").
 * @param {string} [config.apikey] - Optional API key for Bearer authentication.
 * @param {string} prompt  - Full prompt text sent to the model.
 * @yields {string} Text snippets as generated by the model.
 * @throws {Error} If the initial HTTP response is an error.
 */
export async function* generate(config, prompt) {
    let url = config.url || "";
    if (url.endsWith("/")) url = url.slice(0, -1);
    const fetchUrl = url + "/api/generate"; // Text generation endpoint

    const headers = { "Content-Type": "application/json" };
    // Optional authentication support for Ollama servers protected with Bearer token
    if (config.apikey) headers["Authorization"] = "Bearer " + config.apikey;

    // POST request body parameters.
    // `stream: true` enables incremental response mode (NDJSON).
    const bodyParams = { model: config.model, prompt: prompt, stream: true };

    const response = await fetch(fetchUrl, {
        method: "POST",
        headers: headers,
        body: JSON.stringify(bodyParams)
    });

    if (!response.ok) throw new Error(`HTTP ${response.status}`);

    // To read the body incrementally, we use a ReadableStreamDefaultReader.
    // `response.body` is a ReadableStream that emits Uint8Array of bytes.
    const reader = response.body.getReader();
    const decoder = new TextDecoder(); // Converts bytes (Uint8Array) to UTF-8 strings
    let buffer = ""; // Accumulates bytes that don't yet form a complete line

    while (true) {
        // `reader.read()` resolves when data is available or the stream has finished.
        const { done, value } = await reader.read();
        if (done) break; // Server closed the connection: generation complete

        // Accumulate decoded text. The `{ stream: true }` option tells the
        // decoder that there might be multibyte character bytes split across chunks,
        // so it shouldn't emit the character until all bytes are received.
        buffer += decoder.decode(value, { stream: true });

        // Ollama in stream mode separates each JSON object with a newline "\n".
        // Split the buffer by lines to process each JSON separately.
        let lines = buffer.split("\n");

        // The last line may be incomplete (server hasn't sent the final "\n" yet).
        // Extract it from the array and keep it in `buffer` for the next cycle.
        buffer = lines.pop();

        for (const line of lines) {
            const tLine = line.trim();
            if (!tLine) continue; // Ignore empty lines

            try {
                // Each line is a JSON object. We extract the `response` field
                // which contains the next text snippet generated by the model.
                const json = JSON.parse(tLine);
                if (json.response) yield json.response;
                // Note: when `json.done === true`, `json.response` is usually "".
                // The while loop will end on the next `reader.read()` that returns `done: true`.
            } catch (e) {
                // A line might not be valid JSON if the server cut it half.
                // In that case we just ignore it; the next chunk will complete it.
            }
        }
    }
}
