/**
 * @file drivers/anthropic.js
 * @description Communication driver with the Anthropic API (Claude).
 *
 * Anthropic exposes a REST API to interact with its Claude family models
 * (Claude 3 Haiku, Sonnet, Opus, etc.). Unlike other providers, the
 * Anthropic API has some specific authentication and header requirements.
 *
 * AUTHENTICATION:
 * --------------
 * Instead of the standard `Authorization: Bearer <key>` header, Anthropic uses its
 * own `x-api-key: <key>` header. Additionally, it requires specifying the
 * API version with `anthropic-version`.
 *
 * SPECIAL `anthropic-cors-request` HEADER:
 * -------------------------------------------
 * By default, calls to the Anthropic API from a browser are blocked
 * by CORS, as Anthropic does not allow requests from arbitrary origins.
 * The `anthropic-cors-request: true` header enables Anthropic's permissive CORS mode,
 * which allows direct requests from browser extensions or web applications.
 * Without this header, requests from the extension context would be rejected.
 *
 * STREAM FORMAT (Server-Sent Events):
 * ------------------------------------------
 * With `stream: true`, the Anthropic API responds with an SSE
 * (Server-Sent Events) stream. Each event follows the standard format:
 *
 *   event: content_block_delta
 *   data: {"type":"content_block_delta","index":0,"delta":{"type":"text_delta","text":"Hello"}}
 *
 * Relevant events for text extraction are `content_block_delta` type,
 * whose `delta.text` field contains the generated text snippet.
 * Other events like `message_start`, `message_delta`, `message_stop` are ignored.
 *
 * MODEL LISTING ENDPOINT:
 * ---------------------------------
 * GET https://api.anthropic.com/v1/models
 * The response contains a `data` property with an array of model objects,
 * each with an `id` field which is the model's textual identifier.
 */

/**
 * Retrieves the list of available models from the Anthropic API.
 *
 * @param {Object} config - Connection configuration.
 * @param {string} config.apikey - Anthropic API key (x-api-key).
 * @returns {Promise<Array<{name: string}>>} Normalized model list (`name` property).
 * @throws {Error} If the HTTP response is an error.
 */
export async function fetchModels(config) {
    const fetchUrl = "https://api.anthropic.com/v1/models";

    // Headers required by the Anthropic API to list models
    const headers = {
        "x-api-key": config.apikey,              // Anthropic's own authentication method
        "anthropic-version": "2023-06-01",        // API version we want to use
        "anthropic-cors-request": "true"          // Enables CORS from browser contexts
    };

    const res = await fetch(fetchUrl, { headers });
    if (!res.ok) throw new Error("HTTP " + res.status);

    const data = await res.json();

    // The response looks like: { "data": [ { "id": "claude-3-5-sonnet-20241022", ... }, ... ] }
    // Normalize the array so each element has the `name` property that
    // the model selection component in options.js expects.
    if (data.data) {
        return data.data.map(m => ({ name: m.id }));
    }
    return [];
}

/**
 * Generates text from a prompt using the Anthropic Messages API (Claude).
 *
 * This function is an async generator that streams the model response
 * using the Server-Sent Events (SSE) protocol. It emits (`yield`) text snippets
 * as they arrive, allowing the response to be shown progressively.
 *
 * @param {Object} config  - Service configuration.
 * @param {string} config.apikey - Anthropic API key.
 * @param {string} config.model  - Model ID to use (e.g.: "claude-3-5-sonnet-20241022").
 * @param {string} prompt  - Full prompt text.
 * @yields {string} Text snippets as generated by the model.
 * @throws {Error} If the initial HTTP response is an error.
 */
export async function* generate(config, prompt) {
    const fetchUrl = "https://api.anthropic.com/v1/messages"; // Chat/messages endpoint

    const headers = {
        "Content-Type": "application/json",
        "x-api-key": config.apikey,
        "anthropic-version": "2023-06-01",
        "anthropic-cors-request": "true"          // Necessary for calls from the browser
    };

    // Request body according to Anthropic's Messages API specification.
    // `max_tokens` is mandatory in the Anthropic API (unlike OpenAI).
    // We use 4096 as a reasonable limit for long responses.
    const bodyParams = {
        model: config.model,
        max_tokens: 4096,
        messages: [{ role: "user", content: prompt }], // Single-turn message format
        stream: true  // Enables Server-Sent Events mode
    };

    const response = await fetch(fetchUrl, {
        method: "POST",
        headers: headers,
        body: JSON.stringify(bodyParams)
    });

    if (!response.ok) throw new Error(`HTTP ${response.status}`);

    // Reader for the response body as a byte stream
    const reader = response.body.getReader();
    const decoder = new TextDecoder("utf-8");
    let buffer = ""; // Accumulates partial data between network chunks

    while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        // Accumulate text and split into lines to process event by event.
        // SSE uses "\n" as field separator and "\n\n" to separate full events.
        buffer += decoder.decode(value, { stream: true });
        let lines = buffer.split("\n");
        buffer = lines.pop(); // The last line might be incomplete; keep it

        for (const line of lines) {
            const tLine = line.trim();
            if (!tLine) continue; // Empty lines separate SSE events: ignore

            // SSE data fields are prefixed with "data: "
            // "event: " fields indicate event type but we don't process them
            // directly because we read it from the JSON itself (`type` field).
            if (tLine.startsWith("data: ")) {
                const textData = tLine.substring(6); // Remove "data: " prefix
                try {
                    const json = JSON.parse(textData);

                    // The `content_block_delta` event is the one carrying generated text.
                    // Its structure is:
                    //   { "type": "content_block_delta", "delta": { "type": "text_delta", "text": "..." } }
                    if (json.type === "content_block_delta" && json.delta && json.delta.text) {
                        yield json.delta.text;
                    }
                    // Other event types (message_start, message_delta, message_stop, etc.)
                    // contain metadata about the message but not generated text; ignored.
                } catch (e) {
                    // If JSON is incomplete or malformed (rare but possible), ignore it.
                }
            }
        }
    }
}
