/**
 * @file background.js (Chrome version)
 * @description Background script ("service worker") for the Chrome extension.
 *
 * In Chrome Manifest V3 (MV3) extensions, the background script is an
 * ephemeral **Service Worker**, not a persistent background page. This has
 * important implications:
 *
 *  - The service worker is automatically suspended when there are no events to
 *    process, freeing memory and CPU.
 *  - It is automatically reactivated when a new message or event arrives.
 *  - It CANNOT maintain state in global variables between events, as it
 *    may be suspended and re-instantiated. To persist state,
 *    `chrome.storage` must be used.
 *
 * KEY DIFFERENCE WITH FIREFOX:
 * --------------------------------
 * In Firefox MV3, the background script is a persistent ES module (not a service
 * worker), so it can maintain state in memory. In Chrome, it cannot.
 *
 * DIFFERENCE IN FILE DOWNLOADS:
 * ----------------------------------------
 * In Chrome, service workers do not have access to `URL.createObjectURL()` because
 * that method belongs to the browser API (available in windows/pages)
 * and service workers live in a separate worker context.
 *
 * To generate a downloadable URL from a Blob in the Chrome service worker,
 * we use `FileReader.readAsDataURL()`, which converts the Blob into a data URI
 * ("data:text/markdown;base64,..."). This is available in service workers.
 *
 * In Firefox, `URL.createObjectURL()` works because the background is not a
 * real service worker, but a script in a normal extension context.
 *
 * RESPONSIBILITIES OF THIS MODULE:
 * -----------------------------------
 *  1. UNIDIRECTIONAL MESSAGES (`runtime.onMessage`):
 *     - "processSelection" → Download to disk or open result.html with data.
 *     - "fetchModels"      → Query available models from the LLM provider.
 *
 *  2. CONNECTION PORTS (`runtime.onConnect`):
 *     - Manages long-running bidirectional streaming with result.js to
 *       receive and forward text chunks generated by the LLM.
 */

import * as ollama    from './drivers/ollama.js';
import * as openai    from './drivers/openai.js';
import * as anthropic from './drivers/anthropic.js';
import * as gemini    from './drivers/gemini.js';

/**
 * Driver dispatch table indexed by provider type.
 * Allows driver selection with `DRIVERS[serviceType]` without switch/case.
 * @type {Object.<string, {fetchModels: Function, generate: AsyncGeneratorFunction}>}
 */
const DRIVERS = {
    ollama,
    openai,
    anthropic,
    gemini
};

// ============================================================
// UNIDIRECTIONAL MESSAGE LISTENER
// ============================================================
// `chrome.runtime.onMessage` handles single-response requests.
// Returning `true` in the listener indicates the response will be asynchronous
// (necessary when using Promise inside the callback).
// ============================================================
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {

    // ---- ACTION: processSelection ----
    // Received from content script (popup.js / bridge) when the user
    // has selected a page element for processing.
    if (message.action === "processSelection") {

        if (message.type === "disk") {
            // DISK MODE: Download captured content as a Markdown file.
            //
            // IMPORTANT NOTE - DIFFERENCE WITH FIREFOX:
            // In the Chrome service worker, `URL.createObjectURL()` IS NOT available.
            // Instead, we use FileReader to convert the Blob to a base64 data URI,
            // which chrome.downloads.download() can use as a download source.
            //
            // Flow:
            //   Blob → FileReader.readAsDataURL() → "data:text/markdown;base64,..." → download()

            // Sanitize the title to use as a safe filename
            let cleanTitle = message.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
            if (!cleanTitle || cleanTitle.trim() === "") cleanTitle = "article";
            const filename = cleanTitle + ".md";

            const blob = new Blob([message.markdown], { type: "text/markdown" });
            const reader = new FileReader();

            reader.onload = function() {
                // reader.result contains the complete data URI: "data:text/markdown;base64,SGVsbG8..."
                // chrome.downloads.download() accepts data URIs directly as source.
                chrome.downloads.download({
                    url: reader.result, // base64 Data URI of the Markdown content
                    filename: filename,
                    saveAs: true        // Shows the OS native "Save As" dialog
                }).catch(err => {
                    console.error("Download error: ", err);
                });
            };

            // Start asynchronous reading of the Blob as data URI.
            // When finished, the `onload` event defined above is triggered.
            reader.readAsDataURL(blob);

        } else if (message.type === "llm") {
            // LLM MODE: Open result.html to process content with AI.
            //
            // We use storage.local as a data passing channel because:
            //   1. Content might be too long for a URL query string.
            //   2. We cannot send messages to a tab that doesn't exist yet.
            //
            // `executionId` is unique by timestamp to avoid collisions if the user
            // launches multiple requests almost simultaneously.
            const executionId = Date.now().toString();
            chrome.storage.local.set({
                [`exec_${executionId}`]: {
                    markdown:  message.markdown,   // Extracted content (Markdown or raw HTML)
                    title:     message.title,       // Page title (for filename)
                    service:   message.serviceData, // Full LLM service configuration
                    url:       message.url,         // Source URL (for {URL} template)
                    domain:    message.domain,      // Source domain (for {DOMAIN} template)
                    lang:      message.lang,        // HTML document language (<html lang>)
                    syslang:   message.syslang      // System language (navigator.language)
                }
            }).then(() => {
                // Open result.html with the storage key ID in the query string.
                // result.js will read it with URLSearchParams to retrieve data.
                chrome.tabs.create({ url: `result.html?id=${executionId}` });
            });
        }
    }

    // ---- ACTION: fetchModels ----
    // Received from options.js when the user configures a new service.
    // Dynamically queries the list of available models from the configured provider.
    if (message.action === "fetchModels") {
        const type = message.serviceType || "ollama";
        const driver = DRIVERS[type]; // Select driver by type

        if (!driver) {
            sendResponse({
                success: false,
                error: chrome.i18n.getMessage("errUnsupportedService", [""])
            });
            return false; // false = sync response already sent
        }

        // Delegate network request to the corresponding driver.
        // Drivers perform fetch() directly; in Chrome this works in the service worker.
        driver.fetchModels({ url: message.url, apikey: message.apikey })
            .then(models => sendResponse({ success: true, data: { models } }))
            .catch(err  => sendResponse({ success: false, error: err.message }));

        return true; // IMPORTANT: `true` keeps the channel open for async response
    }
});

// ============================================================
// CONNECTION PORTS LISTENER (BIDIRECTIONAL STREAMING)
// ============================================================
// Ports allow long-running bidirectional communication between
// extension pages and the background. Unlike `onMessage`, ports
// can exchange multiple messages without reopening the channel.
//
// result.js opens an "llm-generate" port and sends a "generate" request.
// This listener:
//   1. Receives generation parameters (model, prompt, etc.).
//   2. Creates an async generator from the corresponding driver.
//   3. Iterates over chunks and forwards them one by one through the port.
//   4. Upon completion, sends { type: "done" }.
//   5. On error, sends { type: "error", error: "..." }.
//
// NOTE ON CHROME SERVICE WORKER AND STREAMING:
// The Chrome service worker can be suspended during streaming if there is no
// activity. An active port (`onConnect`) keeps the service worker "alive"
// while the connection is open. result.js manages timeouts and retries
// in case the service worker is unexpectedly suspended.
// ============================================================
chrome.runtime.onConnect.addListener((port) => {
    // Support two port names for historical compatibility
    if (port.name === "ollama-generate" || port.name === "llm-generate") {

        port.onMessage.addListener(async (msg) => {
            if (msg.action === "generate") {
                try {
                    const type = msg.serviceType || "ollama";
                    const driver = DRIVERS[type];

                    if (!driver) {
                        throw new Error(
                            chrome.i18n.getMessage("errUnsupportedService", [type])
                        );
                    }

                    // Get the async generator from the driver.
                    // Each `yield` in the driver produces a text chunk.
                    const generator = driver.generate(
                        { url: msg.url, apikey: msg.apikey, model: msg.model },
                        msg.prompt
                    );

                    // Iterate over chunks and send them to the client (result.js) one by one.
                    // `for await...of` blocks between chunks without consuming CPU,
                    // waiting for each fragment from the LLM server.
                    for await (const chunkText of generator) {
                        port.postMessage({ type: "chunk", chunk: chunkText });
                    }

                    console.log("[Background-Gen] Processing stream has finished.");
                    port.postMessage({ type: "done" }); // Completion signal to client

                } catch (e) {
                    console.error("[Background-Gen] Exception during API request/parsing read:", e);
                    port.postMessage({ type: "error", error: e.message }); // Propagate error to client
                }
            }
        });
    }
});

// ============================================================
// CONTEXT MENUS (CHROME)
// ============================================================
// Creates a context menu when text is selected, displaying available AI services.

async function updateContextMenus() {
    await chrome.contextMenus.removeAll();

    const data = await chrome.storage.local.get("llm_services");
    const servicesList = data.llm_services || [];

    if (servicesList.length === 0) return;

    chrome.contextMenus.create({
        id: "ca-parent",
        title: chrome.i18n.getMessage("extName") || "Content Analyzer",
        contexts: ["selection"]
    });

    servicesList.forEach((m, index) => {
        chrome.contextMenus.create({
            id: `llm-service-${index}`,
            parentId: "ca-parent",
            title: "🤖 " + m.name,
            contexts: ["selection"]
        });
    });
}

chrome.runtime.onInstalled.addListener(() => updateContextMenus());
chrome.runtime.onStartup.addListener(() => updateContextMenus());

chrome.storage.onChanged.addListener((changes, areaName) => {
    if (areaName === "local" && changes.llm_services) {
        updateContextMenus();
    }
});

chrome.contextMenus.onClicked.addListener(async (info, tab) => {
    if (info.menuItemId.startsWith("llm-service-")) {
        const index = parseInt(info.menuItemId.substring("llm-service-".length), 10);
        const data = await chrome.storage.local.get("llm_services");
        const servicesList = data.llm_services || [];
        const serviceData = servicesList[index];

        if (!serviceData) return;

        let domain = "";
        try { if (tab && tab.url) domain = new URL(tab.url).hostname; } catch(e) {}

        const executionId = Date.now().toString();
        const markdown = info.selectionText || "";

        chrome.storage.local.set({
            [`exec_${executionId}`]: {
                markdown:  markdown,
                title:     tab ? tab.title : "",
                service:   serviceData,
                url:       tab ? tab.url : "",
                domain:    domain,
                lang:      "NONE",
                syslang:   navigator.language
            }
        }).then(() => {
            chrome.tabs.create({ url: `result.html?id=${executionId}` });
        });
    }
});
