/**
 * @file background.js
 * @description Background script ("service worker") of the Firefox extension.
 *
 * In Firefox Manifest V3 (MV3) extensions, the background script is an
 * ES module that runs persistently while the extension is active.
 * Unlike Chrome MV3 (where it is an ephemeral service worker), in Firefox MV3
 * the background script can maintain memory state continuously.
 *
 * RESPONSIBILITIES OF THIS MODULE:
 * -----------------------------------
 * This script acts as the centralized "backend" of the extension. Its two
 * main functions are:
 *
 *  1. UNIDIRECTIONAL MESSAGES (`runtime.onMessage`):
 *     - Processes "processSelection" action: when the user selects an element
 *       on the page and clicks a popup button, the content script (popup.js) sends
 *       the captured content here. Depending on the type:
 *       · "disk": generates a Markdown blob and downloads it as a .md file.
 *       · "llm":  saves data to storage and opens a new result.html tab.
 *     - Processes "fetchModels" action: gets the list of available models from
 *       any configured LLM provider (Ollama, OpenAI, Anthropic, Gemini).
 *
 *  2. PERSISTENT CONNECTION PORT (`runtime.onConnect`):
 *     - Manages long-duration bidirectional communication with result.js for
 *       streaming text generated by the LLM. A port (Port) is used instead
 *       of simple messages because streaming can last several minutes and
 *       normal messages have a response timeout.
 *
 * DRIVER IMPORT PATTERN:
 * ------------------------------------
 * Drivers for each LLM provider are in separate modules in `./drivers/`.
 * All are imported at the beginning and indexed in the DRIVERS object to be able to
 * dynamically select the correct driver according to the configured type
 * without needing to use switch/case.
 */

import * as ollama    from './drivers/ollama.js';
import * as openai    from './drivers/openai.js';
import * as anthropic from './drivers/anthropic.js';
import * as gemini    from './drivers/gemini.js';

/**
 * Driver dispatch table.
 * Allows selecting the correct driver with `DRIVERS[serviceType]`,
 * where `serviceType` is the string saved in service configuration
 * (e.g.: "ollama", "openai", "anthropic", "gemini").
 * @type {Object.<string, {fetchModels: Function, generate: AsyncGeneratorFunction}>}
 */
const DRIVERS = {
    ollama,
    openai,
    anthropic,
    gemini
};

// ============================================================
// UNIDIRECTIONAL MESSAGE LISTENER
// ============================================================
// `runtime.onMessage` handles single-response requests from popup.js
// and options.js. The listener returns `true` to indicate to Firefox that the response
// will be asynchronous (necessary when using Promise inside the listener).
// ============================================================
browser.runtime.onMessage.addListener((message, sender, sendResponse) => {

    // ---- ACTION: processSelection ----
    // Received from content script bridge (popup.js) when the user
    // has clicked an element on the page to process it.
    if (message.action === "processSelection") {

        if (message.type === "disk") {
            // DISK MODE: Generates a Markdown file and offers it for download.
            //
            // We use the Blob API to create a temporary URL object in memory.
            // `URL.createObjectURL(blob)` returns a URL of type "blob:moz-extension://..."
            // which only exists while the current tab lives.
            // After 10 seconds we revoke the URL to free memory.
            const blob = new Blob([message.markdown], { type: "text/markdown" });
            const url = URL.createObjectURL(blob);

            // Sanitize page title to use as filename.
            // Replace any non-alphanumeric character with "_" and set to lowercase.
            let cleanTitle = message.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
            if (!cleanTitle || cleanTitle.trim() === "") cleanTitle = "article"; // Fallback if title remains empty
            const filename = cleanTitle + ".md";

            browser.downloads.download({
                url: url,
                filename: filename,
                saveAs: true   // Shows the native OS "Save as" dialog
            })
            .then(() => setTimeout(() => URL.revokeObjectURL(url), 10000))
            .catch(err => {
                console.error("Download error:", err);
                URL.revokeObjectURL(url);
            });

        } else if (message.type === "llm") {
            // LLM MODE: Opens a result tab and passes data via storage.
            //
            // We cannot pass content data as URL parameters (too long)
            // or via messages (tab doesn't exist yet). The solution is:
            //   1. Save data in storage.local with a unique temporary key.
            //   2. Open result.html passing the ID of that key in the query string.
            //   3. result.js reads the ID, retrieves data from storage and deletes it after use.
            //
            // `executionId` is a unique identifier based on timestamp to avoid
            // collisions if the user launches several requests almost simultaneously.
            const executionId = Date.now().toString();
            browser.storage.local.set({
                [`exec_${executionId}`]: {
                    markdown:  message.markdown,   // Content extracted from page (Markdown or HTML)
                    title:     message.title,       // Page title (for filename)
                    service:   message.serviceData, // Full configuration of selected LLM service
                    url:       message.url,         // Page URL (for {URL} template)
                    domain:    message.domain,      // Domain (for {DOMAIN} template)
                    lang:      message.lang,        // HTML document language (<html lang> attribute)
                    syslang:   message.syslang      // User's system language (navigator.language)
                }
            }).then(() => {
                // Open results page passing execution ID in query string.
                // result.js will read it with URLSearchParams to retrieve storage data.
                browser.tabs.create({ url: `result.html?id=${executionId}` });
            });
        }
    }

    // ---- ACTION: fetchModels ----
    // Received from options.js when user types URL or API key for a service.
    // Dynamically gets available models and returns them to populate the combo.
    if (message.action === "fetchModels") {
        const type = message.serviceType || "ollama";
        const driver = DRIVERS[type]; // Select correct driver by type

        // Security check: service type must be one of the supported ones
        if (!driver) {
            sendResponse({
                success: false,
                error: browser.i18n.getMessage("errUnsupportedService").replace("$1", "")
            });
            return false; // false = response already sent (not async)
        }

        // Call `fetchModels` method of the corresponding driver.
        // Resulting list is wrapped in standard response format { success, data }.
        driver.fetchModels({ url: message.url, apikey: message.apikey })
            .then(models => sendResponse({ success: true, data: { models } }))
            .catch(err  => sendResponse({ success: false, error: err.message }));

        return true; // IMPORTANT: `true` keeps the response channel open for the Promise
    }
});

// ============================================================
// CONNECTION PORTS LISTENER (BIDIRECTIONAL STREAMING)
// ============================================================
// `runtime.onConnect` is used to manage long-duration connections.
// Unlike `onMessage` (single-time request/response), ports
// allow sending multiple messages in both directions until disconnected.
//
// In this case, result.js opens an "llm-generate" port and this listener:
//   - Receives "generate" action with request parameters.
//   - Calls asynchronous generator of corresponding driver.
//   - For each text chunk, sends a { type: "chunk", chunk: "..." } message.
//   - When stream ends, sends { type: "done" }.
//   - In case of error, sends { type: "error", error: "..." }.
// ============================================================
browser.runtime.onConnect.addListener((port) => {

    // Allow two port names for historical compatibility
    if (port.name === "ollama-generate" || port.name === "llm-generate") {

        port.onMessage.addListener(async (msg) => {
            if (msg.action === "generate") {
                try {
                    const type = msg.serviceType || "ollama";
                    const driver = DRIVERS[type];

                    if (!driver) {
                        throw new Error(
                            browser.i18n.getMessage("errUnsupportedService").replace("$1", type)
                        );
                    }

                    // Get asynchronous generator from driver.
                    // `driver.generate()` returns an asynchronous iterable object.
                    // Each iteration (`yield`) in the driver corresponds to a text chunk.
                    const generator = driver.generate(
                        { url: msg.url, apikey: msg.apikey, model: msg.model },
                        msg.prompt
                    );

                    // Iterate over all chunks produced by the driver.
                    // `for await...of` waits for each `yield` from the generator, staying
                    // blocked (without consuming CPU) between chunks until a new one arrives.
                    for await (const chunkText of generator) {
                        port.postMessage({ type: "chunk", chunk: chunkText });
                    }

                    console.log("[Background-Gen] Processing stream has finished.");
                    port.postMessage({ type: "done" }); // End signal to client

                } catch (e) {
                    console.error("[Background-Gen] Exception during API parsing request/read:", e);
                    port.postMessage({ type: "error", error: e.message }); // Propagate error to client
                }
            }
        });
    }
});
